command: [
  "uvicorn",
  "server.app:app"
]
env:
  # Application Environment
  - name: 'PORT'
    value: '8080'
  
  # Database Configuration (Azure Databricks PostgreSQL)
  - name: 'DB_HOST'
    value: 'instance-14a1000d-f0b9-4892-b7b8-8a4c4def5d31.database.azuredatabricks.net'
  
  - name: 'DB_PORT'
    value: '5432'
  
  - name: 'DB_NAME'
    value: 'information_extractor'
  
  - name: 'DB_USER'
    value: 'sanabil_app'
  
  # Database Password (using valueFrom for secrets)
  - name: 'DB_PASSWORD'
    valueFrom: lakebase_db_password

  # File Upload Configuration
  - name: 'UPLOAD_BASE_PATH'
    valueFrom: documents_upload_volume

  - name: DATABRICKS_JOB_ID
    valueFrom: information_extraction_job