command:
- uvicorn
- server.app:app
env:
- name: APP_ENV
  value: app
- name: DB_PASSWORD
  valueFrom: lakebase_db_password
- name: UPLOAD_BASE_PATH
  valueFrom: documents_upload_volume
- name: DATABRICKS_JOB_ID
  valueFrom: information_extraction_job
